# Generated by Django 4.2.5 on 2023-10-15 20:32

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.TextField(max_length=10, unique=True)),
                ('is_medical', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospname', models.TextField()),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('pincode', models.IntegerField()),
                ('medstaff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientImage',
            fields=[
                ('patid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('imageFile', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='PatientRelative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('pphone', models.CharField(max_length=10)),
                ('page', models.IntegerField()),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('pincode', models.IntegerField()),
                ('dname', models.TextField()),
                ('dphone', models.CharField(max_length=10)),
                ('patrel', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pname'],
            },
        ),
        migrations.CreateModel(
            name='Vital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempval', models.FloatField()),
                ('spo2val', models.FloatField()),
                ('bpmval', models.FloatField()),
                ('bpval', models.FloatField(default=23)),
                ('entered_at', models.DateTimeField(default=datetime.datetime.now)),
                ('patid', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='elder.patientrelative')),
            ],
            options={
                'ordering': ['entered_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('message', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('removefromlist', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(null=True)),
                ('patid', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='elder.patientrelative')),
                ('staffid', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='elder.medicalstaff')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('encoding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('patid', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='elder.patientrelative')),
            ],
        ),
    ]
