# Generated by Django 4.0.3 on 2022-03-22 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elder', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneModel',
        ),
    ]
