# Generated by Django 5.2.3 on 2025-06-21 13:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elder', '0001_initial'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='imagestore',
        #     name='encoding',
        #     field=models.JSONField(),
        # ),
        migrations.AlterField(
            model_name='imagestore',
            name='patid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elder.patientrelative'),
        ),
        migrations.AlterField(
            model_name='medicalstaff',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medicalstaff',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicalstaff',
            name='hospname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medicalstaff',
            name='medstaff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalstaff',
            name='pincode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='medicalstaff',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notification',
            name='patid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elder.patientrelative'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='staffid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elder.medicalstaff'),
        ),
        migrations.AlterField(
            model_name='patientrelative',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patientrelative',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patientrelative',
            name='dname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patientrelative',
            name='dphone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='patientrelative',
            name='patrel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientrelative',
            name='pincode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='patientrelative',
            name='pphone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='patientrelative',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='vital',
            name='entered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vital',
            name='patid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elder.patientrelative'),
        ),
    ]
