# Generated by Django 4.0.3 on 2022-04-08 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elder', '0002_delete_phonemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempVal', models.FloatField()),
                ('spo2Val', models.FloatField()),
                ('BPMVal', models.FloatField()),
                ('entered_at', models.DateTimeField()),
                ('patientId', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
