# Generated by Django 5.2.1 on 2025-05-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elder', '0002_alter_imagestore_encoding_alter_imagestore_patid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientimage',
            name='patid',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
