# Generated by Django 4.0.3 on 2022-04-08 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elder', '0003_vital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vital',
            name='patientId',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='elder.patientrelative'),
        ),
    ]
