# Generated by Django 5.2.1 on 2025-05-13 18:11

import datetime
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elder', '0003_alter_patientimage_patid_alter_userprofile_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagestore',
            name='encoding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None),
        ),
        migrations.AlterField(
            model_name='imagestore',
            name='patid',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='elder.patientrelative'),
        ),
        migrations.AlterField(
            model_name='medicalstaff',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='medicalstaff',
            name='city',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='medicalstaff',
            name='hospname',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='medicalstaff',
            name='medstaff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='medicalstaff',
            name='pincode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medicalstaff',
            name='state',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='approved_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='notification',
            name='patid',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='elder.patientrelative'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='staffid',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='elder.medicalstaff'),
        ),
        migrations.AlterField(
            model_name='patientrelative',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patientrelative',
            name='city',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patientrelative',
            name='dname',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patientrelative',
            name='dphone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patientrelative',
            name='patrel',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientrelative',
            name='pincode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patientrelative',
            name='pphone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patientrelative',
            name='state',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.TextField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='vital',
            name='entered_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='vital',
            name='patid',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='elder.patientrelative'),
        ),
    ]
