# Generated by Django 4.0.3 on 2022-04-12 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elder', '0004_alter_vital_patientid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vital',
            old_name='BPMVal',
            new_name='bpmval',
        ),
        migrations.RenameField(
            model_name='vital',
            old_name='patientId',
            new_name='patid',
        ),
        migrations.RenameField(
            model_name='vital',
            old_name='spo2Val',
            new_name='spo2val',
        ),
        migrations.RenameField(
            model_name='vital',
            old_name='tempVal',
            new_name='tempval',
        ),
    ]
