# Generated by Django 4.0.3 on 2022-04-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elder', '0005_rename_bpmval_vital_bpmval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vital',
            name='bpval',
            field=models.FloatField(default=23),
        ),
    ]
