# Generated by Django 4.0.3 on 2022-04-20 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elder', '0006_vital_bpval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vital',
            options={'ordering': ['entered_at']},
        ),
    ]
