# Generated by Django 4.0.3 on 2022-05-23 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elder', '0008_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='approved_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
