# Generated by Django 4.0.3 on 2022-05-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elder', '0009_alter_notification_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='approved_at',
            field=models.DateTimeField(null=True),
        ),
    ]
