# Generated by Django 4.0.3 on 2022-05-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elder', '0010_alter_notification_approved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
