# Generated by Django 4.0.3 on 2022-06-16 04:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elder', '0012_notification_removefromlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vital',
            name='entered_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
