# Generated by Django 4.0.3 on 2022-06-20 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elder', '0014_postimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
